// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  isoCode: __t.string().name("iso_code"),
  flag: __t.string(),
  region: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  isBot: __t.bool().name("is_bot"),
  botStrategy: __t.string().name("bot_strategy"),
  balance: __t.f64(),
  gdpScore: __t.f64().name("gdp_score"),
  online: __t.bool(),
});
