// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  attackerId: __t.u64().name("attacker_id"),
  targetId: __t.u64().name("target_id"),
  attackType: __t.string().name("attack_type"),
  status: __t.string(),
  effectDescription: __t.string().name("effect_description"),
  executedAt: __t.timestamp().name("executed_at"),
});
