// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  issuerCountryId: __t.u64().name("issuer_country_id"),
  targetCountryId: __t.u64().name("target_country_id"),
  commodityId: __t.u64().name("commodity_id"),
  reason: __t.string(),
  active: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
});
