// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sellerId: __t.u64().name("seller_id"),
  commodityId: __t.u64().name("commodity_id"),
  qty: __t.f64(),
  pricePerUnit: __t.f64().name("price_per_unit"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
