// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BotTickSchedule = __t.object("BotTickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type BotTickSchedule = __Infer<typeof BotTickSchedule>;

export const Commodity = __t.object("Commodity", {
  id: __t.u64(),
  name: __t.string(),
  symbol: __t.string(),
  basePrice: __t.f64(),
  unit: __t.string(),
});
export type Commodity = __Infer<typeof Commodity>;

export const Country = __t.object("Country", {
  id: __t.u64(),
  name: __t.string(),
  isoCode: __t.string(),
  flag: __t.string(),
  region: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  isBot: __t.bool(),
  botStrategy: __t.string(),
  balance: __t.f64(),
  gdpScore: __t.f64(),
  online: __t.bool(),
});
export type Country = __Infer<typeof Country>;

export const CountryResource = __t.object("CountryResource", {
  id: __t.u64(),
  countryId: __t.u64(),
  commodityId: __t.u64(),
  qty: __t.f64(),
  productionRate: __t.f64(),
});
export type CountryResource = __Infer<typeof CountryResource>;

export const Meta = __t.object("Meta", {
  id: __t.u8(),
  initialized: __t.bool(),
});
export type Meta = __Infer<typeof Meta>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  countryId: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const PriceTickSchedule = __t.object("PriceTickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PriceTickSchedule = __Infer<typeof PriceTickSchedule>;

export const SpotPrice = __t.object("SpotPrice", {
  id: __t.u64(),
  commodityId: __t.u64(),
  price: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type SpotPrice = __Infer<typeof SpotPrice>;

export const TradeHistory = __t.object("TradeHistory", {
  id: __t.u64(),
  sellerId: __t.u64(),
  buyerId: __t.u64(),
  commodityId: __t.u64(),
  qty: __t.f64(),
  price: __t.f64(),
  filledAt: __t.timestamp(),
});
export type TradeHistory = __Infer<typeof TradeHistory>;

export const TradeOffer = __t.object("TradeOffer", {
  id: __t.u64(),
  sellerId: __t.u64(),
  commodityId: __t.u64(),
  qty: __t.f64(),
  pricePerUnit: __t.f64(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type TradeOffer = __Infer<typeof TradeOffer>;

