// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  eventType: __t.string().name("event_type"),
  headline: __t.string(),
  description: __t.string(),
  affectedCommodityId: __t.u64().name("affected_commodity_id"),
  priceMultiplier: __t.f64().name("price_multiplier"),
  active: __t.bool(),
  triggeredAt: __t.timestamp().name("triggered_at"),
});
